app_name: aServ
port: "8080"
log_level: info
auth:
  secret: replace-with-your-secret-key
  expire_hrs: 24
storage:
  path: ./pkg/storage/storage.json
rate_limit:
  enabled: true
  max_per_min: 60
features:
  analytics: true
  image_uploads: true
  audit: true
admin:
  default_username: admin
  default_password: adminpass
  default_email: admin@example.com
